# Development profile configuration
spring:
  datasource:
    url: jdbc:mysql://subscriptiondb-instance-1.c7244oq0k56a.eu-north-1.rds.amazonaws.com:3306/useraccess
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer: https://connect.identity.stagaws.visma.com
          audience: https://gw.access-management.api.odp.aws.stag.visma.net
      client:
        registration:
          visma-connect:
            scopes: publicapi:user:create,publicapi:user:update,publicapi:user:read,publicapi:tenant:userapplicationroles:read, publicapi:tenant:userapplicationroles:update, publicapi:tenant:read, publicapi:tenant:create, publicapi:tenant:application:create,publicapi:tenant:update, publicapi:featuresystem:read,publicapi:tenant:user:read,publicapi:tenant:user:update,publicapi:tenant:application:read
        provider:
          visma-connect:
            token-uri: https://connect.identity.stagaws.visma.com/connect/token

management:
  health:
    db:
      enabled: false

connect:
  public-endpoint: ${CONNECT_PUBLIC_API_URL:https://connect-dev.visma.com/api}

logging:
  level:
    sql: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework:
      transaction:
        interceptor: TRACE
    reactor:
      netty:
        http:
          client: DEBUG    
