# Development profile configuration
spring:
  datasource:
    url: jdbc:mysql://subscriptiondb-instance-1.c7244oq0k56a.eu-north-1.rds.amazonaws.com:3306/useraccess

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer: https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_2yhKQLlD3
      client:
        registration:
          visma-connect:
            scopes: https://public-api.connect.visma.com/publicapi:user:create,https://public-api.connect.visma.com/publicapi:user:update,https://public-api.connect.visma.com/publicapi:user:read,https://public-api.connect.visma.com/publicapi:tenant:userapplicationroles:read,https://public-api.connect.visma.com/publicapi:tenant:userapplicationroles:update, https://public-api.connect.visma.com/publicapi:tenant:read, https://public-api.connect.visma.com/publicapi:tenant:create, https://public-api.connect.visma.com/publicapi:tenant:application:create,https://public-api.connect.visma.com/publicapi:tenant:update, https://public-api.connect.visma.com/publicapi:featuresystem:read,https://public-api.connect.visma.com/publicapi:tenant:user:read,https://public-api.connect.visma.com/publicapi:tenant:user:update,https://public-api.connect.visma.com/publicapi:tenant:application:read
        provider:
          visma-connect:
            token-uri: https://xjcyxjmpvh.execute-api.eu-west-1.amazonaws.com/int/oauth2/token

connect:
  public-endpoint: https://9wjefu9qo6.execute-api.eu-west-1.amazonaws.com/int

management:
  health:
    db:
      enabled: false

logging:
  level:
    sql: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework:
      transaction:
        interceptor: TRACE
    reactor:
      netty:
        http:
          client: DEBUG    
